// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFlowStats(arg1, arg2) {
  return window['go']['main']['App']['GetFlowStats'](arg1, arg2);
}

export function SaveFlow(arg1, arg2) {
  return window['go']['main']['App']['SaveFlow'](arg1, arg2);
}

export function ValidateFlow(arg1, arg2) {
  return window['go']['main']['App']['ValidateFlow'](arg1, arg2);
}
