// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFlowStats(arg1:string,arg2:string):Promise<string>;

export function SaveFlow(arg1:string,arg2:string):Promise<string>;

export function ValidateFlow(arg1:string,arg2:string):Promise<boolean|string>;
